module.exports = [
    {
        name:'北京市',
        code:0,
        parentCode:-1,
    },
    {
        name:'重庆市',
        code:1,
        parentCode:-1,
    },
    {
        name:'天津市',
        code:2,
        parentCode:-1,
    },
    {
        name:'河北省',
        code:3,
        parentCode:-1,
    },
    {
        name:'山西省',
        code:4,
        parentCode:-1,
    },
    {
        name:'内蒙古',
        code:5,
        parentCode:-1,
    },
    {
        name:'辽宁省',
        code:6,
        parentCode:-1,
    },
    {
        name:'吉林省',
        code:7,
        parentCode:-1,
    },
    {
        name:'昌平区',
        code:8,
        parentCode:120
    },
    {
        name:'东城区',
        code:9,
        parentCode:120,
    },
    {
        name:'西城区',
        code:10,
        parentCode:120,
    },
    {
        name:'朝阳区',
        code:11,
        parentCode:120,
    },
    {
        name:'丰台区',
        code:12,
        parentCode:120,
    },
    {
        name:'石景山区',
        code:13,
        parentCode:120,
    },
    {
        name:'海淀区',
        code:14,
        parentCode:120,
    },
    {
        name:'重庆市',
        code:15,
        parentCode:1
    },
    {
        name:'九龙坡区',
        code:16,
        parentCode:15,
    },
    {
        name:'沙坪坝区',
        code:17,
        parentCode:15,
    },
    {
        name:'渝北区',
        code:18,
        parentCode:15,
    },
    {
        name:'北碚区',
        code:19,
        parentCode:15,
    },
    {
        name:'南岸区',
        code:20,
        parentCode:15,
    },
    {
        name:'江津区',
        code:21,
        parentCode:15,
    },
    {
        name:'天津市',
        code:22,
        parentCode:2
    },
    {
        name:'和平区',
        code:23,
        parentCode:22,
    },
    {
        name:'河东区',
        code:24,
        parentCode:22,
    },
    {
        name:'河西区',
        code:25,
        parentCode:22,
    },
    {
        name:'南开区',
        code:26,
        parentCode:22,
    },
    {
        name:'河北区',
        code:27,
        parentCode:22,
    },
    {
        name:'红桥区',
        code:28,
        parentCode:22,
    },
    {
        name:'石家庄市',
        code:29,
        parentCode:3
    },
    {
        name:'唐山市',
        code:30,
        parentCode:3
    },
    {
        name:'秦皇岛市',
        code:31,
        parentCode:3
    },
    {
        name:'邯郸市',
        code:32,
        parentCode:3
    },
    {
        name:'邢台市',
        code:33,
        parentCode:3
    },
    {
        name:'雄安新区',
        code:34,
        parentCode:3
    },
    {
        name:'长安区',
        code:35,
        parentCode:29
    },
    {
        name:'桥西区',
        code:36,
        parentCode:29
    },
    {
        name:'新华区',
        code:37,
        parentCode:29
    },
    {
        name:'井陉矿区',
        code:38,
        parentCode:29
    },
    {
        name:'裕华区',
        code:39,
        parentCode:29
    },
    {
        name:'鹿泉区',
        code:40,
        parentCode:29
    },
    {
        name:'路南区',
        code:41,
        parentCode:30
    },
    {
        name:'路北区',
        code:42,
        parentCode:30
    },
    {
        name:'古治区',
        code:43,
        parentCode:30
    },
    {
        name:'开平区',
        code:44,
        parentCode:30
    },
    {
        name:'丰南区',
        code:45,
        parentCode:30
    },
    {
        name:'丰润区',
        code:46,
        parentCode:30
    },
    {
        name:'海港区',
        code:47,
        parentCode:31
    },
    {
        name:'山海关区',
        code:48,
        parentCode:31
    },
    {
        name:'北戴河区',
        code:49,
        parentCode:31
    },
    {
        name:'青龙县',
        code:50,
        parentCode:31
    },
    {
        name:'昌黎县',
        code:51,
        parentCode:31
    },
    {
        name:'抚宁区',
        code:52,
        parentCode:31
    },
    {
        name:'邯山区',
        code:53,
        parentCode:32
    },
    {
        name:'丛台区',
        code:54,
        parentCode:32
    },
    {
        name:'复兴区',
        code:55,
        parentCode:32
    },
    {
        name:'峰峰矿区',
        code:56,
        parentCode:32
    },
    {
        name:'肥乡区',
        code:57,
        parentCode:32
    },
    {
        name:'永年区',
        code:58,
        parentCode:32
    },
    {
        name:'桥东区',
        code:59,
        parentCode:33
    },
    {
        name:'桥西区',
        code:60,
        parentCode:33
    },
    {
        name:'邢台县',
        code:61,
        parentCode:33
    },
    {
        name:'临城县',
        code:62,
        parentCode:33
    },
    {
        name:'内丘县',
        code:63,
        parentCode:33
    },
    {
        name:'柏乡县',
        code:64,
        parentCode:33
    },
    {
        name:'容城县',
        code:65,
        parentCode:34
    },
    {
        name:'安新县',
        code:66,
        parentCode:34
    },
    {
        name:'雄县',
        code:67,
        parentCode:34
    },
    {
        name:'太原',
        code:68,
        parentCode:4
    },
    {
        name:'大同',
        code:69,
        parentCode:4
    },
    {
        name:'阳泉',
        code:70,
        parentCode:4
    },
    {
        name:'长治',
        code:71,
        parentCode:4
    },
    {
        name:'小店区',
        code:72,
        parentCode:68
    },
    {
        name:'迎泽区',
        code:73,
        parentCode:68
    },
    {
        name:'杏花岭区',
        code:74,
        parentCode:68
    },
    {
        name:'平城区',
        code:75,
        parentCode:69
    },
    {
        name:'云岗区',
        code:76,
        parentCode:69
    },
    {
        name:'新荣区',
        code:77,
        parentCode:69
    },
    {
        name:'城区',
        code:78,
        parentCode:70
    },
    {
        name:'矿区',
        code:79,
        parentCode:70
    },
    {
        name:'郊区',
        code:80,
        parentCode:70
    },
    {
        name:'城区',
        code:81,
        parentCode:71
    },
    {
        name:'郊区',
        code:82,
        parentCode:71
    },
    {
        name:'长治县',
        code:83,
        parentCode:71
    },
    {
        name:'呼和浩特',
        code:84,
        parentCode:5
    },
    {
        name:'包头市',
        code:85,
        parentCode:5
    },
    {
        name:'乌海市',
        code:86,
        parentCode:5
    },
    {
        name:'新城区',
        code:87,
        parentCode:84
    },
    {
        name:'回民区',
        code:88,
        parentCode:84
    },
    {
        name:'玉泉区',
        code:89,
        parentCode:84
    },
    {
        name:'东河区',
        code:90,
        parentCode:85
    },
    {
        name:'昆都仑区',
        code:91,
        parentCode:85
    },
    {
        name:'青山区',
        code:92,
        parentCode:85
    },
    {
        name:'海勃湾区',
        code:93,
        parentCode:86
    },
    {
        name:'海南区',
        code:94,
        parentCode:86
    },
    {
        name:'乌达区',
        code:95,
        parentCode:86
    },
    {
        name:'沈阳市',
        code:96,
        parentCode:6
    },
    {
        name:'大连市',
        code:97,
        parentCode:6
    },
    {
        name:'葫芦岛市',
        code:98,
        parentCode:6
    },
    {
        name:'和平区',
        code:99,
        parentCode:96
    },
    {
        name:'沈河区',
        code:100,
        parentCode:96
    },
    {
        name:'大东区',
        code:101,
        parentCode:96
    },
    {
        name:'中山区',
        code:102,
        parentCode:97
    },
    {
        name:'西岗区',
        code:103,
        parentCode:97
    },
    {
        name:'沙河口区',
        code:104,
        parentCode:97
    },
    {
        name:'连山区',
        code:105,
        parentCode:98
    },
    {
        name:'龙港区',
        code:106,
        parentCode:98
    },
    {
        name:'兴城市',
        code:107,
        parentCode:98
    },
    {
        name:'长春市',
        code:108,
        parentCode:7
    },
    {
        name:'吉林市',
        code:109,
        parentCode:7
    },
    {
        name:'四平市',
        code:110,
        parentCode:7
    },
    {
        name:'南关市',
        code:111,
        parentCode:108
    },
    {
        name:'宽城区',
        code:112,
        parentCode:108
    },
    {
        name:'朝阳区',
        code:113,
        parentCode:108
    },
    {
        name:'昌邑区',
        code:114,
        parentCode:109
    },
    {
        name:'龙潭区',
        code:115,
        parentCode:109
    },
    {
        name:'船营区',
        code:116,
        parentCode:109
    },
    {
        name:'铁西区',
        code:117,
        parentCode:110
    },
    {
        name:'铁东区',
        code:118,
        parentCode:110
    },
    {
        name:'梨树县',
        code:119,
        parentCode:110
    },
    {
        name:'北京市',
        code:120,
        parentCode:0,
    },
]